project:
  type: website
website: 
  title: "Hydroprime"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - text: "software"
        href: data/software/software.qmd
      - capacitacion.qmd
      - contact.qmd
  page-footer:
    left: "Hydroprime"
    right: |
      Made by Hydroprime`
    center: |
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    



