project:
  type: website
website: 
  title: "Hydroprime"
  favicon: /data/images/logo/logo1.png
  twitter-card: true
  site-url: https://hydroprime.github.io
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Productos"
        href: data/software/products.qmd
      - text: "training"
        href: training.qmd
      - text: "contacto"
        href: contact.qmd
    
  page-footer:
    left:
      - icon: linkedin
        href: https://www.linkedin.com/company/hydroprime
      - icon: facebook
        href: https://www.facebook.com/hydroresilient/
      - icon: wordpress
        href: https://hydroprime.wordpress.com/
      - icon: whatsapp
        href: https://wa.me/message/27B6XWJBVALAN1
    right: |
      Made by Hydroprime and Quarto`
    center: |
    
  margin-header: |
      ![](/data/images/logo/logo1.png)
      
format:
  html:
    theme:
      dark: darkly
    css: styles.css
    toc: false




