project:
  type: website
website: 
  title: "Hydroprime"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "software"
        href: data/software/software.qmd
      - text: "training"
        href: training.qmd
      - text: "contacto"
        href: contact.qmd
        
  page-footer:
    left:
      - icon: github
        href: https://github.com/Hydroprime/
      - icon: linkedin
        href: https://www.linkedin.com/company/hydroprime
      - icon: facebook
        href: https://www.facebook.com/hydroresilient/
      - icon: wordpress
        href: https://hydroprime.wordpress.com/ 
    right: |
      Made by Hydroprime and Quarto`
    center: |
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    



