project:
  type: website
website: 
  title: "Hydroprime"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "software"
        href: data/software/software.qmd
      - text: "training"
        href: training.qmd
      - text: "contacto"
        href: contact.qmd
        
  sidebar:
    - title: "Tutorials"
      style: "docked"
      background: light
      contents:
      - text: "training"
        href: training.qmd
        
  page-footer:
    left: "Hydroprime"
    right: |
      Made by Hydroprime`
    center: |
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    



