project:
  type: website

website:
  title: "Hydroprime"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "software"
        href: data/software/software.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



