---
title: "SOPORTE T칄CNICO"
---

# **Contacto**

Para chatear y conocer m치s sobre [**Hydroprime**]{style="color: #045FB4;"}, [haz clic aqu칤](https://wa.me/message/27B6XWJBVALAN1) 游눫游눹

# **Fuentes y Material de apoyo** 

> ## Programaci칩n avanzada en Python para GIS
>
> El curso est치 desarrollado por el Departamento de Geograf칤a de la **Universidad de Pensilvania (Estados Unidos)**, es totalmente gratuito.
>
> para ver el curso, [haz clic aqu칤](https://www.e-education.psu.edu/geog489/home.html)

> ## Cat치logo de Visualizaci칩n de datos
>
> La p치gina contiene informaci칩n sobre los diferentes tipos, caracteristicas y usos de gr치ficos para el aprendizaje sobre la visualizaci칩n de datos.
>
> para ver la p치gina, [haz clic aqu칤](https://datavizcatalogue.com/)

> ## GIS en R
>
> Son tutoriales orientados a usuarios de R, no requieren conocimientos de an치lisis espacial, los tutoriales incluyen datos y ejercicios de apoyo.
>
> para ver los tutoriales, [haz clic aqu칤](https://www.nickeubank.com/gis-in-r/)
